# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./hotelbooking/backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:7000"
    environment:
      MONGO_URI: mongodb://mongo:27016/hotelbooking
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
