# .github/workflows/docker-build.yml
name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    environment:
        name: Production #This is the name of the environment list set for testing on github environment
    name: Build, Test, and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Build and test backend with MongoDB
      - name: Build and test backend with MongoDB
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 20 # Wait for MongoDB to initialize
          docker logs backend
          docker-compose down

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hotelbooking-backend:latest -f hotelbooking/backend/Dockerfile hotelbooking/backend
          docker push ${{ secrets.DOCKER_USERNAME }}/hotelbooking-backend:latest

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hotelbooking-frontend:latest -f hotelbooking/frontend/Dockerfile hotelbooking/frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/hotelbooking-frontend:latest
